### ISSUE TITLE
Composing new types using fluture and typecheck issues

### ISSUE THREAD

**Issue by tb01923** [fluture-js/Fluture#125]
@avaq I know this is closed (https://github.com/fluture-js/Fluture/issues/29)  but I am working on an EitherFuture type leveraging the Sanctuary Either and Fluture.  The implementation of **chain** is not working because the passed function returns the EitherFuture type which fails the fluture type check.

My implementation is:
`
self[chain] = f => {
        return self.getValue()[chain](future => {
            return future[chain](f)
        })
` 
where
`
   self.getValue() 
   //=> either ( future a _ ) ( future _ b ) 
`
and
`
   f(b)
   //=> EitherFuture
`

Any thoughts?  I am leaning towards thinking I cannot build this type through composition - but I really think it would be neat to be able to do so...

**Comment by tb01923** [comment]
Sorry - not really an issue. More of a question.

**Comment by Avaq** [comment]
I can add for certain that disabling type checking in Fluture is not going to make the issue go away. It would simply cause the `EitherFuture` to end up in the internals of Fluture, which expect to be dealing with a `Future`. Likely you'll see something like `future._fork is not a function` down the line. All that type checking in Fluture is doing is detecting values it won't be able to handle as early as possible.

That said, I *know* it's possible to use Monad Transformers to compose a new type with Future as an inner type. We cannot make a transformer for Future (eg, `FutureT(Either)`) but I think we should be able to make an `EitherT(Future)`, which may be able to satisfy your needs. There is an implementation of this [here](https://github.com/fantasyland/fantasy-eithers/blob/master/src/either.js#L62-L98).

I'm going to close the issue because it is not actionable, but feel free to continue the discussion. :)

**Comment by tb01923** [comment]
@Avaq thank you.  I suspect you realize (but want to be be explicit).  I wasn't asking for the type checking to be disabled (the referenced ticket explains the thoughts there), but rather guidance on leveraging this type in compositions.  Thanks for the link - I will investigate.
