### ISSUE TITLE
Unable to recover from thrown exceptions

### ISSUE THREAD

**Issue by Beanow** [fluture-js/Fluture#153]
Below is an example of the issue.

```js
'use strict';
const Future = require('fluture');

const instantCache = Future.cache(Future.of('instantVal'));
const slowCache = Future.cache(Future((rej, res) => {setTimeout(() => res('slowVal'), 50)}));
const brokenChainMapper = () => { throw new Error('Broken') };
const noop = () => {}

try {
	instantCache.chain(brokenChainMapper).fork(noop, noop);
} catch(e) {
	console.log(`Caught instant cache error ${e.message}`);
}

try {
	slowCache.chain(brokenChainMapper).fork(noop, noop);
} catch(e) {
	console.log(`Caught slow cache error ${e.message}`);
}
```

Here the `instantCache` version gets caught and logged. While the `slowCache` one crashes the process like an uncaught exception.

My usecase is to cache a DB connection used for web server request handlers. Then using the try...catch as a last resort to output 500 errors, rather than crash the process.

Tested on node 8.5.0 and fluture 7.1.2.

**Comment by Avaq** [comment]
Hey! :wave: 

What you've demonstrated is a problem with try-catch: it doesn't catch errors thrown in later ticks.

Fluture intentionally does not attempt to solve this problem\*. Instead developers are encouraged not to rely on try/catch for handling expected failures. You case can be one of two:

1. `brokenChainMapper` throws an error because there is a bug in your program. At this point it is safer for the program to crash, as continuing would mean keeping the program in an unexpected state. You can use `process.on('uncaughtException')` to crash "gracefully", but you should eventually crash.
2. `brokenChainMapper` throws an error because an underlying API uses `throw` to signify failure. In this case you should tell Fluture *explicitly* that these kinds of failures are expected, by using `try` or `encase` around this underlying API.

----

\* I'm working on writing a version of Fluture which *does* allow users to recover from thrown exceptions in `fork`, specifically for programs where `fork` is not the same as `main`, such as web servers. In that version, you could deal with the first case somewhat more elegantly. Though until it's included in Fluture, you should use `process.on('uncaughtException')`.

**Comment by Avaq** [comment]
PS: `Future.cache` has nothing to do with it. Try removing calls to it from your example code. :)

**Comment by Beanow** [comment]
I see, that makes sense.

```js
try {
	Future.after(50, 'slowVal').chain(brokenChainMapper).fork(noop, noop);
} catch(e) {
	// Also not caught.
}
```

Using `process.on('uncaughtException')` would not be suitable for sending error responses on the web server level as it could also be a problem unrelated to the request handler, so indeed it looks like we'll have to let it shut down and restart.

It was indeed intended for handling bugs, as restarting would affect uptime and other connected clients whose requests would normally have resolved without issues.

**Comment by Avaq** [comment]
> indeed it looks like we'll have to let it shut down and restart

...and remove the bugs! :)

I will leave this issue (with a modified title) open for documentation of my intention to implement exception recovery.

**Comment by Avaq** [comment]
I'm making good progress towards solving this issue, and I was hoping to include the fix in the 8.0 release, but it's taking too long and the sanctuary-type-classes upgrade was well overdue. So it's been postponed to 9.0.

**Comment by Beanow** [comment]
Looking forward to it! :tada:

**Comment by Avaq** [comment]
Inching ever closer. It also has a nice effect on error messages:

```js
const m = Future.reject('rejected').chainRej(_ => 'wrong')
m.fork(console.error, console.log)
```

```text
Error: TypeError came up while while interpreting a Future.

Future#chainRej expects the function it's given to return a Future.
  Actual: "wrong" :: String
  From calling: _ => 'wrong'
  With: "rejected"

The causing Future:

Future.reject("rejected").chainRej(_ => 'wrong')

    at error
    at someError
    at exception
    at Recovered$interpret [as _interpret]
    at drain
    at settle
    at interpretSequence
    at Sequence$interpret [as _interpret]
    at Sequence.Future$fork [as fork]
```

**Comment by Avaq** [comment]
What should the API look like? Some options for the name are:

* `forkAndRecover`
* `interpret`
* `subscribe`
* `run`

And some options for the signature are:

```hs
Future a b ~> (Error -> Any, a -> Any, b -> Any) -> Cancel
Future a b ~> { onCrash :: Error -> Any, onReject :: a -> Any, onResolve :: a -> Any } -> Cancel
Future a b ~> { Crashed :: Error -> Any, Rejected :: a -> Any, Resolved :: a -> Any } -> Cancel
```

**Comment by Beanow** [comment]
Subscribe seems least preferable to me. It's too much reminiscent of other concepts such as publish-subscribe, event handlers, etc.

Run and interpret are rather ambiguous so the distinction between it and fork is hard to make up from the name.

`forkAndRecover` sounds as if it's a valid way to recover from errors, while it's more a limitation of a crash to part of your software. A specific and early `chainRej` would be the proper way to recover from something.

While the term may be slightly overused. What about `safeFork`? It's a similar term to safety in the sense of sanctuary's safe functions and types. And it nicely distinguishes itself from fork.

**Comment by Avaq** [comment]
I don't like `safeFork` because it gives the impression that you are somehow making your program more safe, while in reality you are taking a risk; The regular `fork` encourages crashing your program when an exception occurs, and that's actually the safest course of action - it ensures that your program will restore to an expected state by forcing it to restart. With crash recovery, you risk leaving your program to run in an unexpected state. Crash recovery makes the assumption that your Future ran in isolation. That all side effects it may have caused will not influence any other part of your program. It's very hard to say for certain that this is the case\*. Essentially crash recovery allows the developer to make that call, but they always take a risk in doing so.

\* Especially if you are calling to third-party functions from within your computations, which you almost always do.

**Comment by davidchambers** [comment]
`riskyFork`, perhaps? :trollface:

**Comment by Avaq** [comment]
Just `trifork` maybe? It also sounds a bit like `try` and implies nothing other than its arity :)

**Comment by Avaq** [comment]
Oh, [apparently](https://www.quora.com/Why-does-a-usual-fork-have-3-tines/answer/Joshua-Engel), they kind of jumped from two to four prongs, so maybe not the greatest analogy, funny nonetheless.
