### ISSUE TITLE
not es5 compatible

### ISSUE THREAD

**Issue by jackmellis** [fluture-js/Fluture#191]
When I attempt to uglify my project I get errors because fluture still contains es6 syntax, I was surprised to find there was no `lib` folder and the `dist` folder in the repo is not included in the npm package.

Do you have any plans to address this?

**Comment by Avaq** [comment]
Hello. Maybe you are using the wrong file.

The `dist` folder is not for use with npm. It only exists loading the library directly from https://rawgit.com/fluture-js/Fluture/master/dist/bundle.js.

I'm not sure why you expect a `lib` folder, because Fluture has never had one. As per `package.json`:

```json
{
  "main": "index.js",
  "types": "index.d.ts",
  "module": "index.mjs.js",
}
```

There are two distributions. The es6 module for use with rollup, and the CJS version for Node. I can safely uglify the CJS `index.js`:

```sh
$ npm i fluture uglify-js
$ ./node_modules/.bin/uglifyjs node_modules/fluture/index.js
(function(global,factory){typeof exports==="object"&&typeof module!=="undefined"?module.exports= ...
``` 

If you want to use the es6 module version, you will have to bundle it using rollup, webpack, babel or something, first.

----

Or maybe I missed something. If you're sure you're using the right file, could you share how you're using Fluture to give me a better understanding of where it fails?

**Comment by jackmellis** [comment]
This is probably my mistake, I am using v6 (because there are no flow type definitions for v7 yet)

**Comment by jshthornton** [comment]
@Avaq I think what Jack is saying here is version 8 of this package's index file has a `const` in it, which isn't supported in ES5.

It's preferred that libraries provide the dists for ES5 support as the library itself will understand what babel plugins it'll need to transpile.
