### ISSUE TITLE
How do you do TDD with Fluture?

### ISSUE THREAD

**Issue by Fl4m3Ph03n1x** [fluture-js/Fluture#260]
Background
-----
I am trying to convert a code snippet from good old Promises into something using Flutures and Sanctuary:

https://codesandbox.io/embed/q3z3p17rpj?codemirror=1

Problem
-----

Now, usually, using Promises, I can uses a library like [sinonjs](http://sinonjs.org/) to stub the promises, i.e. to fake their results, force to resolve, to reject, ect.

This is fundamental, as it helps one test several branch directions and make sure everything works as is supposed to. 

With Flutures however, it is different. One cannot simply stub a Fluture and I didn't find any _sinon-esque_ libraries that could help either.

Questions
-----

1. How do you stub Flutures ?
2. Is there any specific recommendation to doing TDD with Flutures/Sanctuary?

**Comment by yeldiRium** [comment]
I'm not sure how you're going to refactor your code to use Flutures, since you're using libraries which provide you with promises.

But for example assuming `axios.get` is used as if it returns a Fluture, I'd test it something like this:
```javascript
  it("should make a request", async () => {
    const params = { endpoint: "/api/v1/supervisor/status/", timeoutMs: 1000 };

    axios.get.returns(Fluture.of({ status: "OK" }));

    await request(params);

    expect(axios.get).to.have.been.calledOnce;
  });
```

There are no shortcuts in sinonjs or similar libraries (as far as I'm aware of), which give shortcuts for this, but you can return the Flutures manually the way you need them.

Also this is just me brainstorming, since I haven't actually used Fluture in TDD yet. I'm interested in other recommendations for this aswell.

Hope it helps :)

**Comment by Fl4m3Ph03n1x** [comment]
It sure helps, but to use it that way `request` would still have to return a `Promise` ( because of `await` ). 
I did find another helpful set of suggestions in SO:

https://stackoverflow.com/a/51410732/1337392

And in this sandbox:

https://codesandbox.io/embed/04k95z5mzv?codemirror=1
