### ISSUE TITLE
Where is debugMode?

### ISSUE THREAD

**Issue by ArturAralin** [fluture-js/Fluture#312]
I feel self a bit stupid. Where is `.debugMode(Boolean)`? Maybe it was missed in the build?

My fluture version: 10.3.1

**Comment by Avaq** [comment]
Hi @ArturAralin 

Don't worry about it, there has been confusion about this before.

The problem is likely that you're using the modular Fluture build (using `import Future`). This build doesn't expose all functions on the Future constructor - they are *named exports* instead. This is not very apparent from the README, and I should do something about that. It doesn't make it easier that the default export (`Future`), *does* have some functions; They are there to be compliant with [Static Land](https://github.com/rpominov/static-land).

To solve your problem, you could do `import {debugMode} from 'fluture'`, or anything equivalent.

**Comment by ArturAralin** [comment]
Absent of this function in index.ts.d may confuse other developers (like a me). I think need to add this function to index.ts.d

`export function debugMode(debug: boolean): void;`

What do you think about @Avaq?

**Comment by Avaq** [comment]
Oh. You're absolutely right!

**Comment by ArturAralin** [comment]
If it need I can open PR

**Comment by Avaq** [comment]
I'll do it - there are other things missing from index.d.ts as well.

**Comment by ArturAralin** [comment]
Ok. Thanks for the respond

**Comment by ArturAralin** [comment]
That's sad =(
But thanks for fix anyway

**Comment by Avaq** [comment]
> That's sad =(

I'm sorry. It shouldn't be long before the next release, though!
