### ISSUE TITLE
The computation was expected to return a nullary function or void

### ISSUE THREAD

**Issue by tarasowski** [fluture-js/Fluture#330]
Hi there,
I'm currently working with the AWS SDK DynamoDB. Trying to convert callbacks to a Future. 
I'm getting an error s. below. Tried with data.task everything works just fine. But Fluture isn't working.

```
/Users/......./inspection-order/node_modules/fluture/index.js:46
      throw x;
      ^

TypeError: The computation was expected to return a nullary function or void
  Actual: {"API_CALL": function API_CALL() {
      var apiCallEvent = self.apiCallEvent(request);
      apiCallEvent.AttemptCount = attemptCount;
      if (apiCallEvent.AttemptCount <= 0) return;
      apiCallEvent.Timestamp = callTimestamp;
      var latency = Math.round(AWS.util.realClock.now() - callStartRealTime);
      apiCallEvent.Latency = latency >= 0 ? latency : 0;
      var response = request.response;
      if (
        typeof response.retryCount === 'number' &&
        typeof response.maxRetries === 'number' &&
        (response.retryCount >= response.maxRetries)
      ) {
        apiCallEvent.MaxRetriesExceeded = 1;
      }
/........./
at typeError (/Users/...../inspection-order/node_modules/fluture/index.js:146:12)
    at Computation$interpret [as _interpret] (/Users/..../inspection-order/node_modules/fluture/index.js:429:21)
    at Computation.Future$fork [as fork] (/Users/..../inspection-order/node_modules/fluture/index.js:342:17)
    at Object.<anonymous> (/Users/..../inspection-order/index.test.js:49:8)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)

```
This is how the function looks like
```
const getItem = params =>
   Future((rej, res) =>
    dynamodb.getItem(params, (err, data) => err ? rej(err) : res(data)))
```

Added `.API_CALL` and it seems to work. But looks really strange.
--------------- Edit--------------------
```
const getItem = params =>
   Future((rej, res) => 
     dynamodb.getItem(params, (err, data) => err ? rej(err) : res(data)).API_CALL)
```

**Comment by Avaq** [comment]
Hi and welcome @tarasowski! Thank you for getting in touch.

What Fluture is trying to tell you is that it's expecting that you return a cancellation function, like:

```js
Future((rej, res) => {
  dynamodb.getItem(params, (err, data) => err ? rej(err) : res(data))
  return () => { /*this is the cancellation function*/ }
});
```

Alternatively, you're allowed to return nothing in case your operation can't be canclled:

```js
Future((rej, res) => {
  dynamodb.getItem(params, (err, data) => err ? rej(err) : res(data))
  /* returning nothing */
});
```

However, since you're using an arrow function with implicit return, you're returning the result of `dynamodb.getItem(...)`, kind of like this:

```js
Future((rej, res) => {
  return dynamodb.getItem(params, (err, data) => err ? rej(err) : res(data))
});
```

And the return value (`{"API_CALL": function API_CALL() {...}}`) is something Fluture doesn't know what to do with.

Adding `.API_CALL` at the end makes the expression return a function, but it's **not the cancellation function** you want to return. So if that Future would get cancelled, it would call this random function, likely leading to other unexpected behaviour.

What you've run into is quite a common mistake though, and a source of confusion. I'll put some thought into how I might make things clearer.

**Comment by Avaq** [comment]
Note that there's a nicer way to wrap a Node-style callback API, though. Using `node`:

```js
import {node} from 'fluture'
const getItem = params => node (done => dynamodb.getItem (params, done))
```

And since `node` doesn't have this cancellation stuff (because Node style callback API's are typically not cancellable), the implicit return is not being interpreted in some way.

**Comment by tarasowski** [comment]
Hi @Avaq thank you for your reply. It does now work with the changes you proposed. Now I see the point. It's wasn't clear that the function needs to return a cancellation functions. I wasn't reading the type signature `Future :: ((a -> Undefined, b -> Undefined) -> Cancel) -> Future a b` Just expected the same behavior as with `data.task`.
