### ISSUE TITLE
Mapping of mapRej chainLeft to sanctuary

### ISSUE THREAD

**Issue by edgarjrg** [fluture-js/Fluture#369]
Hi !

**Fluture.mapRej**

When i use `S.mapLeft(Fluture)` it looks fine, like pointing to `Fluture.mapRej`, why is mapRej not named mapLeft like other conventions?

**Fluture.chainRej**

What would be the function to use Fluture.chainRej in Sanctuary `S.??(Fluture)` (or even fantasyland) ? 

Why is not called `chainLeft` ?

I understand it's comprehensible from the point of view of fluture to refer to `rejection` and `resolution` branches, as much as `left` and `right`, just want to know if there's any reference that's worth the rebranding of the functions.

so far in fantasyland, sanctuary and ramda i've seen lefts and rights, and the case of fp-ts is sometimes [lefts](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#mapleft-export) and sometimes [firts](https://gcanti.github.io/fp-ts/modules/TaskEither.ts.html#chainfirst-export).

**Comment by Avaq** [comment]
The reason it's called `mapRej`, and not `mapLeft`, is because the function is specialized in the Future type. If it were a general function over bifunctors, such as `S.mapLeft`, then I would've called it `mapRej`. The same goes for `chainRej`.

It might be worth adding a `mapLeft` function to Fluture which is derived from `bimap`, and deprecate `mapRej`, but that's a different matter. The same won't be possible for `chainRej`, as Fantasy Land does not specify `bichain` or anything that could be used to derive a `chainLeft` from.

**Comment by edgarjrg** [comment]
Thank you
