### ISSUE TITLE
Railway Oriented Programming with Fluture

### ISSUE THREAD

**Issue by mohsensaremi** [fluture-js/Fluture#397]
Railway Oriented Programming(ROP) is explained here:
[https://fsharpforfunandprofit.com/rop/](https://fsharpforfunandprofit.com/rop/)

Is there any way to use this pattern with `Fluture`

I can do ROP with these two helper methods like this:
```
const bind = f => x => Future.attempt(() => f(x));
const bindAsync = f => x => Future.tryP(() => f(x));

Future.of("TEST")
    .chain(bind(doThis))
    .chain(bind(doThat))
    .chain(bindAsync(doThisAsync))
    .chain(bindAsync(doThatAsync))
    .chain(bind(doAnotherThing))
    .chain(bindAsync(doAnotherThingAsync))
    .
    .
    .
```

Is there a better way to remove `bind`, `bindAsync` and do binding automatically?

**Comment by Avaq** [comment]
Fluture is inherently a "railway oriented programming" library.
You don't need your own implementation of `bind`, because `chain` *is* monadic `bind`.

Note also that your `bind` is just `Future.encase`, and your `bindAsync` is actually just `Future.encaseP`. So you could have written:

```js
const bind = Future.encase
const bindAsync = Future.encaseP
```

Furthermore, `chain (encase (f))` is equivalent to `map (f)` (assuming `f` doesn't throw). So in that case, your code can be changed altogether into the following:

```js
Future.of("TEST")
.map(doThis)
.map(doThat)
.chain(encaseP(doThisAsync))
.chain(encaseP(doThatAsync))
.map(doAnotherThing)
.chain(encaseP(doAnotherThingAsync))
```

**Comment by Avaq** [comment]
By the way, you are welcome to join our [Gitter chat room](https://gitter.im/fluture-js/Fluture) for small questions like this - usually you can get a faster answer there. There's also a [stack overflow tag](https://stackoverflow.com/questions/tagged/fluture) under which you can ask Fluture-related questions.

**Comment by Avaq** [comment]
Closing this as I don't see further action to be taken.
