### ISSUE TITLE
Getting started guide needed

### ISSUE THREAD

**Issue by cdvv7788** [fluture-js/Fluture#402]
Just some feedback from a newcomer.
I am having issues getting started with the setup. I tried running several of the examples provided in the code, but I just ended up getting `.map` or `.pipe` does not exist. Also, the examples are for documenting the API, not for specific use cases (events, fetching a json, basic things, etc).
The main Readme is more focused on what `fluture` can do, and what is a `future`, not in how to use the library, specifics on common installation paths (I use webpack, and I tried importing directly from `index.js`, didn't work).

Check for example the `rxjs` docs. https://rxjs-dev.firebaseapp.com/guide/overview. 
In the very first screen, you get an example with the most basic use case you can have, and that is easy to reproduce in your project. There is also a very short description of what the project is about (`Fluture` already has that). Even if you don't understand the description, the example gives you more context and makes it easier to understand.

Obviously, I don't have the knowledge to help with this, but an official getting started guide can reduce the entry barrier for the library. This looks like the best library around for this specific use case, but the lack of documentation may be holding it back to a niche. Maybe there is already one and I missed it? (needs more visibility?)

**Comment by Avaq** [comment]
@cdvv7788 Are you taking those examples from the latest version of the documentation? It seems you might be using a different version of Fluture from the version of the documentation you are reading.

**Comment by cdvv7788** [comment]
Well, I couldn't find clear information (or I am just slow xD) to get started, so I googled around. That is why I am not asking for a better documentation, just something to get started. The current documentation was not enough for a complete newbie to the library, and should be something easy to add by someone familiar. A real example of how to handle events with fluture (maybe sanctuary too?) or some specific things like that. Does that make sense?

**Comment by Avaq** [comment]
Aha. I don't think it's because you're slow. We've just released version 12 of Fluture, which represents the first (and probably only) major overhaul to the API. Most of the examples and articles you'll find out there will not yet be using the new API.

You've pointed me to a gap in the ecosystem we've created when releasing version 12: There's very little introductory material for Fluture version 12. It's a good thing you bring this to my attention, as I hadn't really considered it like that before.

For now, you could have a look at [the list of breaking changes](https://gist.github.com/Avaq/ee2c6c819db4c37258e9a226e6380a38) and try to keep those in mind when reading examples written for Fluture version 11 and down. Also please feel free to ask any questions you might have on the [Gitter channel](https://gitter.im/fluture-js/Fluture). I'd be happy to help out with the problem you've described as "I just ended up getting `.map` or `.pipe` does not exist", for example.

For the coming months, we'll be working on filling this aforementioned gap. For starters, I'm thinking I'll write an introductory article about Fluture. There's also plans to release an interview where I'll be talking, among other things, about the design philosophy for Fluture.

**Comment by lichaar** [comment]
I was just about to submit a new issue for this. It would be really great to have an absolute beginner friendly documentation on how to get started and the wonders of Fluture.

I wasn't able to understand anything here until I googled and read dozen of articles on how using Fluture makes me happier.

**Comment by Avaq** [comment]
> It would be really great to have an absolute beginner friendly documentation -- @lichaar 

> I'm thinking I'll write an introductory article about Fluture -- me

I have actually done this, and it's pretty much finished. I will publish it on Monday and let you know!

**Comment by Avaq** [comment]
@lichaar @cdvv7788 @jderochervik Published: https://dev.to/avaq/fluture-a-functional-alternative-to-promises-21b

**Comment by Avaq** [comment]
I closed this issue via the PR that links the introductory article I've written. If you feel it is not sufficient, feel free to reopen the issue.
