### ISSUE TITLE
Access computation value as return value

### ISSUE THREAD

**Issue by akolnati** [fluture-js/Fluture#416]
Hi, Firstly thanks for the wonderful package. 

I have a simple function that reads a file and returns the name (from example)

```
const getPackageName = file =>
  node(done => {
    readFile(file, "utf8", done);
  })
    .pipe(chain(encase(JSON.parse)))
    .pipe(map(x => x.name));
```

and then i try to access the computation output like below but doesn't work.

```
const pckName = getPackageName("package.json").pipe(
  fork(console.error)(value => value)
);

```

how can i return the output of getPackName to be stored in pckName (assuming pckName will be returned as http response or passed to another function). I have tired the below as well but not sure how to resolve a future

```
const eventualPackageName = node(done => readFile("package.json", "utf8", done))
  .pipe(chain(encase(JSON.parse)))
  .pipe(chain(encase(x => x.name)))
  .pipe(
    map(data => {
      log("debug")("Read, parsed, and traversed the package data");
      return data;
    })
  );
```

I am new to FP so it may be more of a FP usage query. Appreciate the help.

**Comment by akolnati** [comment]
Will ask on Gitter as this a query more than a issue

**Comment by Avaq** [comment]
> Hi, Firstly thanks for the wonderful package.

You're welcome. And thank you! :tophat:

> how can i return the output of getPackName [to a variable synchronously]

Your question is quite similar to this one: https://stackoverflow.com/questions/50361976/convert-fluture-future-to-folktale-result

The short answer is you cannot. There's actually no abstraction in JavaScript with which you can do this, because it's a restriction of the language itself.

That said, there's a variety of reasonable alternatives.

1. Access the value in a `map` or `chain`, or any other transformation. As long as you need to transform the value somehow, synchronously or asynchronously, there's no reason to extract it from the Future.
2. Access the value by [consuming the Future](https://github.com/fluture-js/Fluture#consuming-futures). You can use various different shapes of callbacks, or even a Promise, to execute a Future and continue operating on its values.
3. You can use a coroutine to transform the Future in a synchronous-looking way. So this is just like `1`, but the code will look more like how you wanted it to look:
    ```js
    const main = go(function*(){
      const packageName = yield getPackageName("package.json")
      return `The package is named ${packageName}!`;
    });
    ```
    Of course, `main` now is yet another Future, so you still have to consume it in the end. Just like with Promises, once a function is async, the function calling it must also becomes async, all the way down to the root of your program. The only difference is that a Promise consumes itself, and a Future has to be explicitly consumed, ideally at the root of your program and nowhere else.

> Will ask on Gitter as this a query more than a issue

I'm okay with questions being asked here on GitHub. It's just that sometimes it might take a little while longer for me to notice.

**Comment by akolnati** [comment]
Thanks. This helps a lot
