### ISSUE TITLE
Why does encaseP / attemptP accepts only one parameter?

### ISSUE THREAD

**Issue by GrayStrider** [fluture-js/Fluture#419]
It works well enough for something like `fetch`, but what about functions that take several arguments? I would expect to have it spread arguments and having multiple overloads in TS definitions, up to 10 or so. That's usual practice in my experience.
Let's take `axios.get`: what if I want to pass `config` as my second argument?

I tried all the different things with spread operator and such, but couldn't make it work.

**Comment by GrayStrider** [comment]
`fluture-axios` seems to have found a workaround (haven't checked out it's TS typings yet), but the question still stands

**Comment by Avaq** [comment]
> having multiple overloads in TS definitions, up to 10 or so

Fluture's API contains no overloaded functions by design. In my experience, overloaded functions are more difficult to compose and abstract over. I have recently started to draft an article explaining this philosophy in more depth, and I should be able to finish it in the coming months, in case you're interested.

> what if I want to pass `config` as my second argument

You can handle this as such:

```js
const myFunction = param1 => param2 => encaseP (param3 => (
  promiseFunction (param1, param2, param3))
))
```

Or if you don't want a curried function:

```js
const myFunction = (param1, param2, param3) => attemptP (() => (
  promiseFunction (param1, param2, param3))
))
```

It used to be that Fluture had `encaseP2` and `encaseP3` for binary and ternary functions respectively, but they were removed in Fluture 12 as they were a common source of confusion: https://gist.github.com/Avaq/ee2c6c819db4c37258e9a226e6380a38#encasep2-and-encasep3-removed

As shown by the upgrade guide, you can also use `compose` and `curry` to create myFunction in point-free style:

```js
const get = compose (encaseP) (curry2 (axios.get))
```

**Comment by GrayStrider** [comment]
Thanks a lot, `attemptP` seemed to be just what I needed. Really glad how this turned out:
```TS
const encaseMultiArg =
	<Err, Res, T extends (...args: any[]) => Promise<any> = any>
	(func: T) => (...args: Parameters<T>) =>
		attemptP<Err, Res> (() => func (...args))
```

```TS
const axiosF = encaseMultiArg<AxiosError, AxiosResponse> (axios.get)

const get = (url: string) =>
	axiosF (url, { headers: '' })
		.pipe (map (pipe (prop ('data'))))
		.pipe (mapRej (rej => rej.code ?? 'Error'))

describe ('axios', () => {
	const base = 'http://www.example.com',
		path = '/resource', url = base + path
	beforeEach (() => {
		nock (base)
			.get (path)
			.reply (200, 'done')
	})
	
	test ('passes when request returns data', (done) => {
		expect.assertions (1)
		get (url).pipe (fork
			(done) (res => {
				expect (res).toStrictEqual ('done')
				done ()
			}),
		)
	})
	
	test ('passes when rejects', (done) => {
		expect.assertions (1)
		get ('***').pipe (fork
			(rej => {
				expect (rej).toStrictEqual ('ECONNREFUSED')
				done ()
			}) (done),
		)
	})
})
```
Dang, tabs are freaking huge on GitHub

**Comment by GrayStrider** [comment]
```TS
import { attemptP } from 'fluture'

const toTheFuture =
	<Err, Res, T extends (...args: any[]) => Promise<any> = any>
	(func: T) => (...args: Parameters<T>) =>
		attemptP<Err, Res> (() => func (...args))

export default toTheFuture
```
🎉
