### ISSUE TITLE
Exception not throwing in Jest tests

### ISSUE THREAD

**Issue by stevenyap** [fluture-js/Fluture#77]
Hi, I faced a very interesting issue when Fluture is ran in [Jest](https://facebook.github.io/jest/) tests:

```javascript
// Jest test
// works
it('error is caught by Jest without another chain', () => {
  return new Promise((resolve, reject) => {
    return Future.of(1)
      .chain(() => { throw new Error('error') })
      .fork(reject, resolve)
  })
})

// does not work
it('error is not caught by Jest but instead timeouts', () => {
  return new Promise((resolve, reject) => {
    return Future.of(1)
      .chain(Future.fromPromise(Promise.resolve))
      .chain(() => { throw new Error('error') })
      .fork(reject, resolve)
  })
})

// works
it('error is caught by Jest when encapsulated in Future.try', () => {
  return new Promise((resolve, reject) => {
    return Future.of(1)
      .chain(Future.fromPromise(Promise.resolve))
      .chain(() => Future.try(() => { throw new Error('error') }))
      .fork(reject, resolve)
  })
})
```

In the second test case, the exception thrown in the Future is not bubbled up into the promise.
Hence the promise is not rejected and the test case timed out since nothing rejects or resolves it.
It seems like the Future has swallowed the exception!

Jest needs to catch the exceptions otherwise `expect` cannot work.
This issue is causing me to wrap all my `expect` statements in Future.try or else my test cases will not work.

I would like to know how Fluture re-throws the exception so that I can resolve this.
Any help to point out where in the source code for me to look into for possible solution is greatly appreciated too.

**Comment by Avaq** [comment]
> I would like to know how Fluture re-throws the exception

Here's the misconception. Besides for `try` and `encase`, Fluture never catches, nor re-throws exceptions. Let's go over the different cases and identify what *really* happens.

----

> error is caught by Jest without another chain

Since all code inside the Promise is synchronous (`Future.of(1)` resolves synchronously, and `throw` does too), the exception is thrown *during* the execution of the computation given to `new Promise`, which causes the Promise to catch it and set its internal state to rejected. The `reject` or `resolve` callbacks are never actually called.

----

> error is not caught by Jest but instead timeouts

The throwing of the error is actually delayed, because `Promise.resolve` waits a tick. This means that the thrown error could not be caught by the Promise constructor, much like the following:

```js
try{
  setTimeout(() => { throw new Error('Kaputt') }, 100)
}catch(e){
  //never reached.
}
```

----

> error is caught by Jest when encapsulated in Future.try

This is the *only* case where the Error is propagated to the rejection branch of the *Future*, and eventually makes it into the rejection branch of the Promise via the `reject` callback passed to `fork`.

----

If you wish to learn more about the reason Fluture does not catch exceptions, I've [written about error handling](https://github.com/fluture-js/Fluture/wiki/Comparison-to-Promises#error-handling) in the wiki. I realize this is not ideal for working with assertions (the ones that throw exceptions anyway), and if I have to use those, I personally just go through the trouble of wrapping them in `Future.try`.

**Comment by stevenyap** [comment]
Hi @Avaq thanks for your detailed explanation!
