### ISSUE TITLE
Feature Request: Add ChainPromise

### ISSUE THREAD

**Issue by stevenyap** [fluture-js/Fluture#78]
NodeJS and a lot of libraries/frameworks use promises.
Hence, I often find myself chaining promises like this:

```javascript
export const doSomething = () => {
  return Future.of(1)
    .chain(Future.fromPromise(() => /* a promise */ ))
    .chain(Future.fromPromise(() => /* a promise */ ))
    .chain(Future.fromPromise(() => /* a promise */ ))
}
```

I think if we have a `.chainPromise` function that allows user to write the above as:

```javascript
export const doSomething = () => {
  return Future.of(1)
    .chainPromise(() => /* a promise */ )
    .chainPromise(() => /* a promise */ )
    .chainPromise(() => /* a promise */ )
}
```

It is pure sugar syntax but I think it will creates a lot of developer happiness.
Please let me know if this is something Fluture library should adopt and I can contribute the code for it.

**Comment by Avaq** [comment]
Hi @stevenyap,

It's a blurry line between functionality that should be in the library, and functionality that may be considered relatively easy to implement in user-land.

Therefore I'd like to share some alternative approaches to this problem, in order to identify if you really need this new method. This kind case is exactly what people refer to when they say function composition is more powerful than method-chaining. With composition (`pipe` and `compose`), I can easily define `chainPromise` myself, and mix it in with Fluture provided functions:

```js
import {compose, pipe} from 'sanctuary' //Many libraries provide these
import {Future, fromPromise, chain} from 'fluture'

const chainPromise = compose(chain, fromPromise)

export const doSomething = pipe([
  Future.of,
  chain(x => /* a Future */ ),
  chainPromise(x => /* a Promise */ )
])
```

----

I notice you're using new ES features. There is also a proposed [bind operator](https://github.com/tc39/proposal-bind-operator) which would allow intermixing user-defined functions with fluent chains:

```js
const chainPromise = function(f){ this.chain(Future.fromPromise(f)) }
export const doSomething = () =>
  Future.of(1)
  .chain(x => /* a Future */ )
  ::chainPromise(x => /* a Promise */ )
```

----

I see that the ease of just having a method is appealing, but I fear that there are many potential such methods and worry that drawing that blurry line more clearly beyond the point of "sugar over a composition of two functions" may lead to an inflation of surface area that might in the end make the library more daunting for new users.

**Comment by stevenyap** [comment]
Hi @Avaq thank you for the clear explanation and the time to propose alternatives! I agree with your perspective that too many sugar functions may inflate the surface area of the library. :)
